- name: demo on using shell module
  hosts: all
  tasks:
    - name: Running uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Printing the system uptime 
      ansible.builtin.debug:
        msg: Value of the uptime is {{OUT.stdout}} 
 