- name: demo on previlige escalation
  hosts: all
  tasks:
    - name: Running uptime command
      ansible.builtin.shell: id
      register: OUT
    - name: Printing user details
      ansible.builtin.debug:
        msg: Username is {{OUT.stdout}} 