- name: demo on previlige escalation
  hosts: all
  tasks:
    - name: Running uptime command
      ansible.builtin.shell: id
      register: OUT
    - name: Printing the system uptime 
      ansible.builtin.debug:
        msg: Value of the uptime is {{OUT.stdout}} 